### ISSUE TITLE
Browser time handling is wonky. Time delta will be huge and reward 1000s of score.

### ISSUE THREAD

**Issue by ShawSumma** [soryy708/parallax-jump#2]
To repeat this bug leave the game running overnight and open it again, Occasionally the browser will wake your tab just to check in.

Sometimes this cause the parallax-jump's internal timer to award the player with many points.

See attatched.
<img width="924" alt="cheater" src="https://user-images.githubusercontent.com/28312141/211149985-ade13dc9-05c4-4b30-aa2d-f8af56dcc3ef.png">

**Comment by soryy708** [comment]
Nice one.

Instead of fixing this, I decided to redesign the scoring mechanic, so this bug is obsolete.

See: https://github.com/soryy708/parallax-jump/commit/045f8d41258f60aa1b2db6cb1765f84eb3a2d607
